translator: "GoogleTranslator"
start: "de"
goal: "de"
api_keys:
  GoogleTranslator: "XXX"
  DeeplTranslator: "XXX"

flow:
  de:
    fr:
      es:
        fr:
    de:
      es:
      fr:
        sv:
  fr:
    en:
  en:
  fi:
    de:
      fr:
        es:
          fr:
      de:
        es:
        fr:
          sv:
  sv: