name: Fast-Forward Label

on:
  pull_request:
  issue_comment:
    types: [created]

# avoid running multiples
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ff-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch origin ${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.head.ref }}
      - run: git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
      - run: |
          if [[ $(git merge-base --is-ancestor ${{ github.event.pull_request.base.ref }}  ${{ github.event.pull_request.head.ref }}) ]]; then
            echo "FFL=false" >> "$GITHUB_ENV"
          else
            echo "FFL=true" >> "$GITHUB_ENV"
          fi
      - uses: actions-ecosystem/action-add-labels@v1
        if: env.FFL == 'true' 
        with:
          labels: fast-forward
      - uses: actions-ecosystem/action-remove-labels@v1
        if: env.FFL == 'false' 
        with:
          labels: fast-forward
      - uses: mshick/add-pr-comment@v1
        if: env.FFL == 'true' 
        with:
          message: |
            Hurray, this PR is `/fast-forward`-able
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
